### ISSUE TITLE
THE GRID

### ISSUE THREAD

**Issue by elsalvadordali** [elsalvadordali/green-smile#6]
This is by far going to be the trickiest to implement.

The idea: we're going to divide the screen into a grid. 5x6

```
_______________
__|__|__|__|__
__|__|__|__|__
__|__|__|__|__
__|__|__|__|__
__|__|__|__|__
__|__|__|__|__
```
 

HTML/CSS version:
We need to make 30 css classes of EACH plant.. unfortunately. It's more repetitive than anything, but it should look like this:

.rose-1x1 {
background-image: url('to-rose.jpg');
background-position: (calculate to make it in the top-left most grid area);
etc
}

.rose-2x1 will be the CSS class for a rose plant in this position:

```
_______________
__|x |__|__|__
__|__|__|__|__
__|__|__|__|__
__|__|__|__|__
__|__|__|__|__
__|__|__|__|__
```

.peony-3x3 will be the CSS class for a peony plant in this position: 
```

_______________
__|__|__|__|__
__|__|__|__|__
__|__|x |__|__
__|__|__|__|__
__|__|__|__|__
__|__|__|__|__
```

I hope you can see why this is annoying, but necessary. 

react.js: 
we need to get the coordinates of where the user clicks, and calculate which grid it would be in. Then, apply that class to the parent div, so the flower displays. 

When user clicks on a grid, we need to fetch the journal entry they wrote for that day.

**Comment by AshM10** [comment]
[X] garden (parent) is a grid 5x6 displaying only a single month's garden. : check
[X] should be responsive- html plus media query on index.css : check
[X] created garden css
[X] grid would have boxes (soil) : check , needs sizing
[X] the boxes would be div class kids (soil): check
[X ] listening for a mouse event ⬆️ , then get coordinates

[ ] And the user will select where the plant will grow on the grid
[ ] We're going to record the date of the journal entry in the database, plant, and position in the grid
